dist: focal
language: cpp
git:
  depth: 1

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V

addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
    packages:
      - cmake=3.19

jobs:
  include:
    #################################################################################
    # Linux / GCC
    # GCC 4.8 and older doesn't support C++14
    #################################################################################
    # gcc 10
    - os: linux
      name: Linux / gcc 10
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10

    #################################################################################
    # Linux / clang
    #################################################################################
    # clang 11
    - os: linux
      name: Linux / clang 11
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-11
          packages:
            - clang-11
            - g++-10
      env:
        - CC=clang-11
        - CXX=clang++-11
    # clang 10
    - os: linux
      name: Linux / clang 10
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-10
          packages:
            - clang-10
            - g++-10
      env:
        - CC=clang-10
        - CXX=clang++-10

    #################################################################################
    # macosx
    #################################################################################
    # osx (xcode 12.2)
    - os: osx
      name: macOs / xcode 12.2
      osx_image: xcode12.2

    #################################################################################
    # Windows
    #################################################################################
    # Windows (Windows server 1803)
    # Not working for now
    # - os: windows
