dist: focal
language: cpp
git:
  depth: 1

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V

jobs:
  include:
    #################################################################################
    # Linux / GCC
    #################################################################################
    # gcc 10
    - os: linux
      name: Linux / gcc 10
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - g++-10
            - cmake=3.19*
            - cmake-data=3.19*
      env:
        - CC=gcc-10
        - CXX=g++-10
        - PATH="/usr/bin:$PATH" # Find newly installed cmake binary first

    #################################################################################
    # Linux / clang
    #################################################################################
    # clang 11
    - os: linux
      name: Linux / clang 11
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-11
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - clang-11
            - g++-10
            - cmake=3.19*
            - cmake-data=3.19*
      env:
        - CC=clang-11
        - CXX=clang++-11
        - PATH="/usr/bin:$PATH" # Find newly installed cmake binary first
    # clang 10
    - os: linux
      name: Linux / clang 10
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-10
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - clang-10
            - g++-10
            - cmake=3.19*
            - cmake-data=3.19*
      env:
        - CC=clang-10
        - CXX=clang++-10
        - PATH="/usr/bin:$PATH" # Find newly installed cmake binary first

    #################################################################################
    # macosx
    #################################################################################
    # osx (xcode 12.2)
    - os: osx
      name: macOs / xcode 12.2
      osx_image: xcode12.2
      addons:
        homebrew:
          packages:
            - cmake
          update: true

    #################################################################################
    # Windows
    #################################################################################
    # Windows (Windows server 1803)
    # Not working for now
    # - os: windows
